management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: always

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://eureka-server:${EUREKA_SERVER_PORT}/eureka/