spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: api-gateway
    web:
        resources:
            add-mappings: false
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}

    cloud:
        gateway:
            server:
                webflux:
                    routes:
                        -   id: user-service
                            uri: lb://user-service
                            predicates:
                                - Path=/api/v1/users/**

                        -   id: user-service
                            uri: lb://user-service
                            predicates:
                                - Path=/api/v1/auth/**

                        -   id: product-service
                            uri: lb://product-service
                            predicates:
                                - Path=/api/v1/products/**

                        -   id: media-service
                            uri: lb://media-service
                            predicates:
                                - Path=/api/v1/media/**

                    globalcors:
                        cors-configurations:
                            '[/**]':
                                allowed-origins:
                                    - "http://localhost:4200"
                                    - "http://0.0.0.0:4200"
                                allowed-methods: "*"
                                allowed-headers: "*"
                                allow-credentials: true

management:
    endpoints:
        web:
            cors:
                allowed-headers: "*"
                allowed-methods: GET,POST,PUT,DELETE,OPTIONS
                allowed-origins: "http://0.0.0.0:4200"
                allow-credentials: true

server:
    ssl:
        enabled: true
        key-store: classpath:keystore.p12
        key-store-password: ${KEY_STORE_PASSWORD}
        key-store-type: PKCS12
        key-alias: ${KEY_ALIAS}