spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: eureka-server
    web:
        resources:
            add-mappings: false
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}

server:
    port: ${EUREKA_SERVER_PORT}